[tox]
envlist = py,coverage-report,typing,lint
isolated_build = True

[testenv]
description = Run pytest against {envname}.
runner = uv-venv-lock-runner
setenv =
    JIRA_USERNAME = "USER"
    JIRA_PASSWORD = "PASS"
commands =
    pytest --cov=jiradataproxy --cov-branch --cov-report= {posargs}

[testenv:coverage-report]
description = Compile coverage from each test run.
package = skip
deps = coverage[toml]>=5.0.2
depends =
    py
commands = coverage report

[testenv:typing]
description = Run mypy.
commands =
    mypy src/jiradataproxy tests
package = skip
dependency_groups =
    dev
    typing

[testenv:lint]
description = Lint codebase by running prek.
package = skip
commands = prek run --all-files
uv_sync_flags = --only-group, lint

[testenv:run]
description = Run the development server with auto-reload for code changes.
usedevelop = true
commands = uvicorn jiradataproxy.main:app --reload
